version: '3.4'

services:
  agricore-abm-object-relational-mapping:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - POSTGRES_CONNECTIONSTRING=Host=agricore-abm-database;Port=5432;Database=agricore-abm-database;Username=rw_dev;Password=rw_dev

    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro